### ISSUE TITLE
Estado del mongoDB

### ISSUE THREAD

**Issue by alu0100886870** [alu0100825893/proyecto-equipo-com#5]
Nota: Está en mi rama temporal "miguel". Hay que hacer merge
**Conseguido:**
Guarda datos
Muestra los botones
Arreglado eso de que se conecte y desconecte muchas veces el Mongo (lo que dijo Cassiano hace mucho)
Colocados en una columna derecha fija

**Por hacer:**
Que al hacer click ponga lo que contiene en el "textArea" (fácil)
Arreglar refrescado de menos de 4 elementos:
_A falta de hacer uno asíncrono, he dejado una función JavaScript que recargue la página cuando se introduce un nuevo dato (antes había que hacerlo manualmente), es mejor eso que nada, pero tendré que solucionarlo._

**Comment by alu0100825893** [comment]
No me funciona a mi. De momento lo dejo sin merge hasta que vea porque
